### ISSUE TITLE
Can't get MIDI IN to work (chrome 38)

### ISSUE THREAD

**Issue by lukephills** [cwilso/midi-synth#11]
Hi Chris,

I'm using Chrome 38 with the MIDI flag enabled but I can't get your synth (or drum machine) to connect with any of my MIDI controllers. 

I've enabled the chrome flag and restarted. I've also installed the jazz-plugin even though I wasn't sure if I needed it. What steps need to be taken for this to work?

Thank you

**Comment by janbiasi** [comment]
You have to enable the <code>requestMidiAccess</code> method in your chrome flags; Try to open [chrome://flags/](chrome://flags/#enable-web-midi] and search for "requestMidi.." and press enable :smile_cat:

**Comment by cwilso** [comment]
Should be fixed now.

**Comment by lukephills** [comment]
Hi @cwilso, it's still not working for me. It detected that a keyboard was connected; 'KEYBOARD' in the select box, but pressing the keys didn't do anything. Then I disconnected the keyboard and refreshed the page multiple times and it still has 'KEYBOARD' in the select box (when no midi controller is connected).

@janbiasi I don't have a `requestMidiAccess` option in chrome flags. There's only an 'Enable Web MIDI API' which is activated.

**Comment by cwilso** [comment]
@lukephills - I'm not sure what's going on.  I'm not getting midi messages delivered in my current stable (42.0.2311.135) either; however, it works fine in Beta channel, and also in Canary.  Try installing Canary and see if it works; Stable is going to 43 very soon.
